export const ADD_FOOD = 'ADD_FOOD';
export const DELETE_FOOD = 'DELETE_FOOD';
export const INIT_FOODS = 'INIT_FOODS';
export const RESET_FOODS = 'RESET_FOODS';
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const UPDATE_TARGET_CALORIE_RANGE = 'UPDATE_TARGET_CALORIE_RANGE';
